# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd5032f1725ca0de6805cf2168450cf69d20ce90394c889fd9506c0bf7c5e50fa3df0d14e5b300b53f1c139875f5ecd580b590fa2389612c6736caca40bbde04

test:
  secret_key_base: 1d9c5bb865488fe5bbd84e0f8bb2cb7a55cf76fe6d07f5b23b991bfbba13a0d634af8e310ef786e4ad96b459270e3e477458c1b9d003d5c977aecf2737521678

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
